/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systeminvoice;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Consultation extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultation
     */
    
    public Consultation() throws SQLException {
        initComponents();
           
        
        
        
        
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclient = new javax.swing.JTable();
        BtnSearch = new javax.swing.JButton();
        txtD = new javax.swing.JTextField();

        jLabel1.setText("Customer Inquiry");

        jLabel2.setText("N of Document");

        tblclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Document", "Names", "Lastnames", "Productcode", "TypeProduct"
            }
        ));
        jScrollPane1.setViewportView(tblclient);
        if (tblclient.getColumnModel().getColumnCount() > 0) {
            tblclient.getColumnModel().getColumn(0).setHeaderValue("Document");
            tblclient.getColumnModel().getColumn(1).setHeaderValue("Names");
            tblclient.getColumnModel().getColumn(2).setHeaderValue("Lastnames");
            tblclient.getColumnModel().getColumn(3).setHeaderValue("Productcode");
            tblclient.getColumnModel().getColumn(4).setHeaderValue("TypeProduct");
        }

        BtnSearch.setText("Search");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        txtD.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(BtnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnSearch)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
       String camp = txtD.getText();
       String where ="";
       if(!"".equals(camp)){
           where ="WHERE document = '" +camp+ "'";
       }
        try {
              DefaultTableModel model = new DefaultTableModel();
              tblclient.setModel(model);
              PreparedStatement ps = null;
              ResultSet rs = null;
              Conexion conn = new Conexion();
              Connection con = conn.getConexion();
              String sql = "SELECT document, names, lastnames, ProductCode, NameProduct FROM clients "+where;
              System.err.println(sql);
              ps = con.prepareStatement(sql);
              rs = ps.executeQuery();
               ResultSetMetaData rsMd =rs.getMetaData();
                int Columns=rsMd.getColumnCount();
                model.addColumn("document");
                  model.addColumn("names");
                    model.addColumn("lastnames");
                      model.addColumn("ProductCode");
                        model.addColumn("NameProduct");
                        int[] wide = {70, 100, 100, 90, 90};
                        for (int x = 0; x < Columns; x++)
                        {
    tblclient.getColumnModel().getColumn(x).setPreferredWidth(wide[x]);
            }
                while(rs.next()){
                     Object [] row =new Object [Columns];
                       for (int t = 0; t < Columns; t++) {
                    row [t]=rs.getObject(t+1);
                }
                model.addRow(row);
            }
                
        
        }catch (SQLException ex) {
        System.err.println(ex.toString());
        
        }
    }//GEN-LAST:event_BtnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblclient;
    private javax.swing.JTextField txtD;
    // End of variables declaration//GEN-END:variables
}
